### ISSUE TITLE
fast charge does not work

### ISSUE THREAD

**Issue by Danig24** [ananjaser1211/Helios_8890#2]
I have a problem with fast Charging, now I am using ROM Floyd 3.0 One UI 2.1 Cronos Kernel v5.
By connecting the charger with active fast charge, it connects and disconnects successively.
In the Floyd v2.0 ROM and Cronos Kernel v4.0 it worked correctly, as long as it activates the Store_mode option in the hKtweaks battery section, I don't know if it is a problem with my phone or the kernel.
The first time this happened to me was when I upgraded the Kernel from v4.0 to v4.5 in Floyd v2.0, the only way for fast charging to work for me is to go back to the v4.0 kernel and activate Store_mode.
I don't know how to send more information that can be useful
i apologize for any inconvenience caused.
Translated with Google.

**Comment by ananjaser1211** [comment]
STORE_MODE limits the charging speed to 700mAh . which is no where near fast charging, or normal AC charge speeds.

if you flash V4 and enable store mode, you basically locked your charging speed. i dont see how this is a fix

i tested it on my device on Floyd V3 and i tested on blackdiamond v9 (compiled the same kernel but pie variant)

Both fast charge normally. so the issue is something on your end, possibly damaged cables or AC Adapter.

**Comment by Danig24** [comment]
ok then i will try different cables or ac adapter.

I tried another kernel and it was doing the same, so it must be because of what you told me.

thanks for your answer.
